spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.26.137/inventory?usessl=false
spring.datasource.username=root
spring.datasource.password=sRQGkmasjgAaw8HOXS2I1WGj
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:N4Iyyr8qrzZCMx1jARSSW1i8@172.21.186.243/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true